name: stable_diff
channels:
  - default
  - conda-forge
dependencies:
  - python=3.9
  - tensorflow
  - matplotlib
  - pip
  - pip:
    - keras-cv
    - customtkinter
    - fastapi
    - "uvicorn[standard]"